name: build-test-deploy
  on: push
    jobs:
      runs on: ubuntu-latest
      steps:
      -name:checkout repo
      user: actions/checkout@v3
      -name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
      -run: npm install
      -run: npm run build



  

