name: hello-world.yml
on: push
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
      steps:
       -name: check out repository code
       user: actions/checkout@v3
       -run: echo "$(cat hello_world.txt)"
       
